# Generated by Django 3.1.5 on 2021-01-14 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='master',
        ),
        migrations.AddField(
            model_name='master',
            name='certificate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='service.certificate'),
        ),
    ]
