# Generated by Django 3.1.5 on 2021-01-14 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210114_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='certificate',
            new_name='certificates',
        ),
    ]
