# Generated by Django 3.1.5 on 2021-01-14 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20210114_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='masters', to='service.master'),
        ),
    ]
